Rename *.HOT to *.yaml and update templates descriptions

diff --git a/xp5k_no_frontend.yaml b/xp5k_no_frontend.yaml
--- a/xp5k_no_frontend.yaml
+++ b/xp5k_no_frontend.yaml
@@ -1,5 +1,5 @@
 # This describes what is deployed by this template.
-description: Bootstrap Puppet server with Heat on Chameleon
+description: "Deploys Openstack Liberty using xp5k. Unlike Grid'5000 or xp5k.HOT, there is no frontend here, xp5k runs from the puppet-server node"
 
 # This defines the minimum Heat version required by this template.
 heat_template_version: 2015-10-15
@@ -8,22 +8,23 @@ heat_template_version: 2015-10-15
 # how they should be configured.
 resources:
   # Setting up resources (Instance and IP)
+  router_port:
+    type: OS::Neutron::Port
+    properties:
+      name: router-port
+      network: sharednet1
+
   controller_floating_ip:
     type: OS::Nova::FloatingIP
     properties:
       pool: ext-net
 
-  puppet_server_floating_ip:
-    type: OS::Nova::FloatingIP
-    properties:
-      pool: ext-net
-
-  controller:
+  puppet_server:
     type: OS::Nova::Server
     properties:
-      name: controller
+      name: puppet-server
       flavor: baremetal
-      image: CC-Ubuntu14.04
+      image: g5k_ubuntu_min
       key_name: { get_param: key_name }
       networks:
          - network: sharednet1
@@ -32,13 +33,30 @@ resources:
         #!/bin/bash
         # Insecure key, will be removed by frontend
         echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNjtV7RI8vs/IOqwyFRbtb4PNibk6Ju8Hyv2CZk799/66rPW7Q4us6kMUuIUQK8vM6UuByGzsD8eeyGwDjwOmc12mYM0du2s05ABSL8L5L1ddDiRRUbxBEosLb9opZ64/TmjniOcfXdR1qqgm2dVf+MfS977h9c5VH4Kzvc9PiQf50I8IWoNtN0+zxiIJiAkssEXi/emjKTSMYrpwn9DYou559KC24CdgCr2WkTBDDjPzRVgu9OlGEIoPDfHyRUT99b8lkBrtLvlo5dTACdXRXmhW18TRst4TJDI7x8A4+n6SzAC9MYTDWzwcEEEwrzai+CUI86lNBLxLItch+/HuN root@INSECURE" > /root/.ssh/authorized_keys
+        chown root:root /tmp && chmod 777 /tmp
+
+  controller:
+    type: OS::Nova::Server
+    properties:
+      name: controller
+      flavor: baremetal
+      image: g5k_ubuntu_min
+      key_name: { get_param: key_name }
+      networks:
+         - network: sharednet1
+      scheduler_hints: { reservation: { get_param: reservation_id } }
+      user_data: |
+        #!/bin/bash
+        # Insecure key, will be removed by frontend
+        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNjtV7RI8vs/IOqwyFRbtb4PNibk6Ju8Hyv2CZk799/66rPW7Q4us6kMUuIUQK8vM6UuByGzsD8eeyGwDjwOmc12mYM0du2s05ABSL8L5L1ddDiRRUbxBEosLb9opZ64/TmjniOcfXdR1qqgm2dVf+MfS977h9c5VH4Kzvc9PiQf50I8IWoNtN0+zxiIJiAkssEXi/emjKTSMYrpwn9DYou559KC24CdgCr2WkTBDDjPzRVgu9OlGEIoPDfHyRUT99b8lkBrtLvlo5dTACdXRXmhW18TRst4TJDI7x8A4+n6SzAC9MYTDWzwcEEEwrzai+CUI86lNBLxLItch+/HuN root@INSECURE" > /root/.ssh/authorized_keys
+        chown root:root /tmp && chmod 777 /tmp
 
   puppet_server:
     type: OS::Nova::Server
     properties:
-      name: puppet_server
+      name: puppet-server
       flavor: baremetal
-      image: CC-Ubuntu14.04
+      image: g5k_ubuntu_min
       key_name: { get_param: key_name }
       networks:
          - network: sharednet1
@@ -83,15 +101,16 @@ resources:
             Host *
               StrictHostKeyChecking no
               HashKnownHosts no" >> /root/.ssh/config
+
             # Configure /etc/hosts
             puppet_server_ip="$(/sbin/ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}')"
             echo "
-            #Puppet needs to resolv server and client IP
             $puppet_server_ip puppet-server puppet-server.openstacklocal
             $controller_ip controller controller.openstacklocal" >> /etc/hosts
             scp /etc/hosts controller:/etc/hosts
-            # Setup script to run
-            echo '#!/bin/bash
+            #Clone repo and configure Ruby
+            apt-get install -y git screen build-essential
+            chown root:root /tmp && chmod 777 /tmp
             cd /root/
             git clone https://github.com/dloup/xp5k-openstack -b CC_test
             apt-add-repository -y ppa:brightbox/ruby-ng
@@ -101,25 +120,39 @@ resources:
             source setup_env.sh
             gem install bundler
             bundle install
+            # Adapt scenario tasks to CC network 
+            export host_ip=$(/sbin/ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}')
+              ## TACC
+            if [[ $host_ip =~ 10\.40\.[0-1]\.[0-9]{1,3} ]]; then
+              public_net_cmd="cmd << %{neutron subnet-create public 10.40.0.0/23 --name public-subnet --gateway 10.40.1.254 --disable-dhcp --allocation-pool start=$router_ip,end=$router_ip}"
+              ## UC
+            elif [[ $host_ip =~ 10\.140\.8[0-3]\.[0-9]{1,3} ]]; then
+              public_net_cmd="cmd << %{neutron subnet-create public 10.140.80.0/22 --name public-subnet --gateway 10.140.83.254 --disable-dhcp --allocation-pool start=$router_ip,end=$router_ip}"
+            else
+              echo "Can't create network configuration because the controller host is not on the TACC sharednet neither on the UC sharednet"
+              exit 1
+            fi
+            #Using "^" as separator because "/" is in the string $public_net_cmd
+            sed -i "s^#INSERT_PUBLIC_NET_CONF_HERE^$public_net_cmd^" /root/xp5k-openstack/scenarios/liberty_starter_kit/tasks/scenario.rb
+            # Setup script to run
+            echo '#!/bin/bash
+            cd /root/xp5k-openstack
             export HOME=/root
-            rake run' >> /root/run.sh
-            # Run and save logs
+            source setup_env.sh
+            rake run
+            echo "press any key to exit screen"
+            read' > /root/run.sh
             chmod u+x /root/run.sh
-            /root/run.sh > /root/rake_out.log 2>&1
+            screen -dm -S rakerun -s /bin/bash /root/run.sh
           params:
             $controller_ip: { get_attr: [controller, first_address] }
+            $router_ip: { get_attr: [router_port, fixed_ips, 0, ip_address] }
 
   controller_ip_association:
     type: OS::Nova::FloatingIPAssociation
     properties:
       floating_ip: { get_resource: controller_floating_ip }
       server_id: { get_resource: controller }
-
-  puppet_server_ip_association:
-    type: OS::Nova::FloatingIPAssociation
-    properties:
-      floating_ip: { get_resource: puppet_server_floating_ip }
-      server_id: { get_resource: puppet_server }
 
 # The parameters section gathers configuration from the user.
 parameters:
